server:  
  port: 8090
  session-timeout: 60
mybatis:  
     mapperLocations: classpath:mapper/**/*.xml
     typeAliasesPackage: com.example.pojo
     mapperScanPackage: com.example.mapper
     configLocation: classpath:config/mybatis_config.xml
  
mysql:  
    datasource:  
        readSize: 1  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath:/mapper/**/*.xml
        configLocation:  classpath:/config/mybatis_config.xml
        write:  
           url: jdbc:mysql://192.168.26.38:3306/bms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
           username: root
           password: 123456
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read01:  
           url: jdbc:mysql://192.168.26.38:3316/bms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
           username: root
           password: 123456
           driver-class-name: com.mysql.jdbc.Driver  
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat